source 'https://rubygems.org'

gem 'rails', '4.2.0'

#For flexible serialization
gem 'active_model_serializers'

gem 'sqlite3'


group :test do
  gem 'database_cleaner'
  gem 'faker'
  gem 'rspec-rails', '~> 3.0.0'
  gem 'shoulda-matchers', require: false
  gem 'rspec-collection_matchers'
  gem 'factory_girl_rails'
end
